---
- name: "configuration play."
  hosts: all
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_port: "22"
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  environment:
    - ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    - TYPEORM_CONNECTION: "postgres"
    - TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    - TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
    - TYPEORM_MIGRATIONS_DIR: "./src/migrations"

  roles:
    - deploy
