- name: "upgrade packages."
  become: yes
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["tar"]
    state: latest
    update_cache: yes

- name: "Upload project"
  become: yes
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Build node service
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build
